---
# tasks file for ls_role
- name: install ls_extended
  become: yes
  become_user: "{{ item }}"
  shell: rm -rf ~/mygit ~/.bin; git clone https://github.com/Electrux/ls_extended.git ~/mygit && cd ~/mygit && ./build.sh && mkdir ~/.bin && cp bin/ls_extended ~/.bin
  with_items: "{{ user }}"
